name: Deploy to WPE 
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: mattselbywpe
        # Deploy Options
        SRC_PATH: "wp-content/themes/genesis-block-theme/"
        REMOTE_PATH: "wp-content/themes/genesis-block-theme/"
